services:
  postgres:
    image: postgres:latest
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Linh1234!@#$"
      POSTGRES_DB: "AkidoTrainingWebAPIContext"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - productnetwork

  webapi:
    build:
      context: ./AkidoTrainingWebAPI
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      productnetwork:
    restart: on-failure

networks:
  productnetwork: {}

volumes:
  pgdata: {}
