version: "3.9"

services:
  postgres:
    image: postgres:latest
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Linh1234!@#$"
      POSTGRES_DB: "AkidoTrainingWebAPIContext"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - productnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=AkidoTrainingWebAPIContext;Username=postgres;Password=Linh1234!@#$"
    networks:
      - productnetwork
    restart: on-failure

networks:
  productnetwork: {}

volumes:
  pgdata: {}